export const generateSampleData = (days) => {
    // Generate sample matches data; this is a placeholder for dynamic data
    return [
        {
            fixtureId: 'LLR1BA9',
            date: '2024-02-18',
            time: '19:00:00',
            playerA1: 'Nicholas Smith',
            idA1: 'NS005',
            privacyA1: true,
            clubA1: 'Club A1',
            regionA1: 'Region A1',
            countryA1: 'USA',
            playerCountryA1: 'USA',
            categoryA1: 'O30',
            genderA1: 'Male',
            dobA1: '1990-01-01',
            clubAddressA1: '123 Club St, City, Country',
            latA1: '40.7128',
            lngA1: '-74.0060',
            playerA2: 'Max Lewin',
            idA2: 'ML006',
            privacyA2: false,
            clubA2: 'Club A2',
            regionA2: 'Region A2',
            countryA2: 'USA',
            playerCountryA2: 'USA',
            categoryA2: 'O30',
            genderA2: 'Male',
            dobA2: '1992-02-02',
            clubAddressA2: '456 Club St, City, Country',
            latA2: '40.7128',
            lngA2: '-74.0060',
            playerB1: 'Antoine Miller',
            idB1: 'AM009',
            privacyB1: false,
            clubB1: 'Club B1',
            regionB1: 'Region B1',
            countryB1: 'USA',
            playerCountryB1: 'USA',
            categoryB1: 'O30',
            genderB1: 'Male',
            dobB1: '1988-03-03',
            clubAddressB1: '789 Club St, City, Country',
            latB1: '40.7128',
            lngB1: '-74.0060',
            playerB2: 'Alex Robinson',
            idB2: 'AR010',
            privacyB2: false,
            clubB2: 'Club B2',
            regionB2: 'Region B2',
            countryB2: 'USA',
            playerCountryB2: 'USA',
            categoryB2: 'O30',
            genderB2: 'Male',
            dobB2: '1989-04-04',
            clubAddressB2: '101 Club St, City, Country',
            latB2: '40.7128',
            lngB2: '-74.0060',
            gamesScore: '0-2',
            result: '0-6 0-6',
            sport: 'padel',
            matchType: 'P4A Box Leagues',
            weight: '1.0',
            sanctioned: 'ES',
            exclude: false
        },
        {
            fixtureId: 'BDR1BE2',
            date: '2024-02-18',
            time: '19:00:00',
            playerA1: 'Anna Bidwell',
            idA1: 'AB243',
            privacyA1: false,
            clubA1: 'Club A1',
            regionA1: 'Region A1',
            countryA1: 'USA',
            playerCountryA1: 'USA',
            categoryA1: 'O30',
            genderA1: 'Female',
            dobA1: '1991-05-05',
            clubAddressA1: '123 Club St, City, Country',
            latA1: '40.7128',
            lngA1: '-74.0060',
            playerA2: 'Luke Fletcher',
            idA2: 'LF209',
            privacyA2: false,
            clubA2: 'Club A2',
            regionA2: 'Region A2',
            countryA2: 'USA',
            playerCountryA2: 'USA',
            categoryA2: 'O30',
            genderA2: 'Male',
            dobA2: '1993-06-06',
            clubAddressA2: '456 Club St, City, Country',
            latA2: '40.7128',
            lngA2: '-74.0060',
            playerB1: 'Harvey Barrow',
            idB1: 'HB181',
            privacyB1: false,
            clubB1: 'Club B1',
            regionB1: 'Region B1',
            countryB1: 'USA',
            playerCountryB1: 'USA',
            categoryB1: 'O30',
            genderB1: 'Male',
            dobB1: '1987-07-07',
            clubAddressB1: '789 Club St, City, Country',
            latB1: '40.7128',
            lngB1: '-74.0060',
            playerB2: 'Sam Gill',
            idB2: 'SG254',
            privacyB2: false,
            clubB2: 'Club B2',
            regionB2: 'Region B2',
            countryB2: 'USA',
            playerCountryB2: 'USA',
            categoryB2: 'O30',
            genderB2: 'Male',
            dobB2: '1986-08-08',
            clubAddressB2: '101 Club St, City, Country',
            latB2: '40.7128',
            lngB2: '-74.0060',
            gamesScore: '0-2',
            result: '0-6 0-6',
            sport: 'padel',
            matchType: 'P4A Box Leagues',
            weight: '1.0',
            sanctioned: 'ES',
            exclude: false
        }
    ];
};